### ISSUE TITLE
Some issues with the latest versions of Rust

### ISSUE THREAD

**Issue by haraldgrove** [ban-m/hla_haplotyper#1]
Hello

It looks like the latest version of Rust is causing some issues when compiling jtk.

With the latest version of Rust (1.70.0) I'm getting this error:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> haplotyper/src/lib.rs:1:12
  |
1 | #![feature(is_sorted)]
  |            ^^^^^^^^^
```

When I install the latest nightly build (1.72.0-nightly), I get this error: 
```
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/harald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.51/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^
```

After looking for different nightly builds, I found that installing 1.68.0-nightly made it compile, so possibly the documentation needs to be updated.

**Comment by ban-m** [comment]
Thanks for the feedback!
I just updated the `Cargo.lock` so that the `proc-macro` will not cause a problem (hopefully).
Could you compile `jtk` with the latest & nightly toolchain?

(Edit: Maybe `cargo clean` is needed before re-compiling)

**Comment by haraldgrove** [comment]
Thank you for the update. 

The 1.72.0-nightly build compiles without issues now.

I still get an error with the latest stable build (1.70.0):
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> cli/src/lib.rs:1:12
  |
1 | #![feature(fs_try_exists)]
  |            ^^^^^^^^^^^^^
```

**Comment by ban-m** [comment]
Thank you very much! I do not remember when, but years ago I decided to use [`std::fs::try_exists()`](https://doc.rust-lang.org/std/fs/fn.try_exists.html) because the official manual recommended it (!).

Today, [`std::path::Path::try_exists`](https://doc.rust-lang.org/std/path/struct.Path.html#method.try_exists) does a similar job, and the stable toolchain can compile JTK (commit 5e3d9b6).

Could you confirm this?

**Comment by snurk** [comment]
Worked for me on 1.71.1 stable

**Comment by ban-m** [comment]
Thank you for confirming the build!
