### ISSUE TITLE
Convert GFA to phased assembly 

### ISSUE THREAD

**Issue by bsb2014** [ban-m/hla_haplotyper#5]
Hi there

Could you please let me know how to convert the GFA result to phased fasta?

Thanks

**Comment by ban-m** [comment]
Hi,

In general, I think there is no obvious way to split an assembly graph into two phased haplotypes. This is especially true in the output of JTK, as JTK sometimes outputs a sub-optimal assembly graph with complicated bubbles.
In my case, I manually split the contigs into two phased contigs.

If the question is how to convert a GFA file into a FASTA file, the following command would be OK.

cat $GFA | awk '($1 ~ /^S/){print ">" $2 "\n" $4}' > $FASTA

You can also get the number of copies, i.e. whether they are phased or not, by checking the `cp` tag on each record of the data.

**Comment by ban-m** [comment]
By the way, the output format is based on the GFA format version 2 (http://gfa-spec.github.io/GFA-spec/GFA2.html). If there are any problems with the output format of the JTK, could you let me know?

**Comment by bsb2014** [comment]
The format looks good (see below)

H       VN:Z:2.0
U       cp:i:4  tig_0042 tig_0044 tig_0059 tig_0091 tig_0094 tig_0101

What does the cp:i:4 mean here?

Thanks

**Comment by bsb2014** [comment]
By the way, I did not find outputs    *sam and *coverage.tsv

The command line is
~/src/jtk pipeline -p  ~/src/jtk.toml

**Comment by ban-m** [comment]
The `cp` tag represents the number of copies of a contig. In your case, these contigs have copy numbers of four, indicating that there are several unresolved repeats.

Regarding the SAM and the coverage track, it appears that there are at least 100 contigs in your output. In this situation, JTK may have stopped assembly before generating the consensus sequences, alignments, and coverage tracks.

In my opinion, there are three scenarios for this case;
1. JTK is not strong enough to assemble the region you are trying to assemble (JTK cannot handle a region longer than 10M bp or many identical copies),
2. The coverage was sufficient to assemble (I recommend 60x), or
3. the input long reads were not "long" enough (I recommend reads with N50 > 50Kbp, Max > 100Kbp.

**Comment by bsb2014** [comment]
Thanks for your suggestion.
