### ISSUE TITLE
GFA2 visualization

### ISSUE THREAD

**Issue by snurk** [ban-m/hla_haplotyper#6]
Thanks for the exciting new development! Any recommendations on visualizing the answer? Or maybe producing a GFA1 output as an option?

**Comment by ban-m** [comment]
Thanks!
I use GfaViz (https://github.com/ggonnella/gfaviz) for vizualization. It is very easy to install and use.
There is a program to convert a GFA2 file into the GFA1 format (https://github.com/edawson/gfakluge), but I have not tested yet.
