### ISSUE TITLE
jtk build failed

### ISSUE THREAD

**Issue by dmjask** [ban-m/hla_haplotyper#7]
After installing cargo ( 1.72.1 (103a7ff2e 2023-08-15)) and minimap2 (2.26-r1175) I have attempted installing JTK using the guide.
When running `cargo build --release`, as well as `cargo check && cargo build --release`, both produce the same warning:

`warning: build failed, waiting for other jobs to finish...`

which is preceded by this error:

`error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-I" "src/edlib/include" "-Wall" "-Wextra" "-Wall" "-Wextra" "-O3" "-g" "-o" "/net/fs-2/scale/OrionStore/ScratchProjects/Transpose/doja/jtk/target/debug/build/edlib_sys-b0ee97c476634a05/out/src/edlib/src/edlib.o" "-c" "src/edlib/src/edlib.cpp" with args "c++" did not execute successfully (status code exit status: 1).`

Would greatly appreciate any help

**Comment by ban-m** [comment]
Thank you for the feedback!
Could you check whether you have a cpp compiler on your system (i.e., type `c++ --version`)?
If the error persists, could you shere your system information and dump the stderr message produced by `cargo build`? (It is OK to dump a very long log)

**Comment by dmjask** [comment]
c++ version 10.2.0
Must've been some odd issue, as removing everything and restarting from scratch resulted in correct installation.
